/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServiciosRouteImport } from './routes/servicios'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServiciosSlugRouteImport } from './routes/servicios.$slug'

const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosSlugRoute = ServiciosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServiciosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/servicios': typeof ServiciosRouteWithChildren
  '/servicios/$slug': typeof ServiciosSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/servicios': typeof ServiciosRouteWithChildren
  '/servicios/$slug': typeof ServiciosSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/servicios': typeof ServiciosRouteWithChildren
  '/servicios/$slug': typeof ServiciosSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/servicios' | '/servicios/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/servicios' | '/servicios/$slug'
  id: '__root__' | '/' | '/servicios' | '/servicios/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ServiciosRoute: typeof ServiciosRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/$slug': {
      id: '/servicios/$slug'
      path: '/$slug'
      fullPath: '/servicios/$slug'
      preLoaderRoute: typeof ServiciosSlugRouteImport
      parentRoute: typeof ServiciosRoute
    }
  }
}

interface ServiciosRouteChildren {
  ServiciosSlugRoute: typeof ServiciosSlugRoute
}

const ServiciosRouteChildren: ServiciosRouteChildren = {
  ServiciosSlugRoute: ServiciosSlugRoute,
}

const ServiciosRouteWithChildren = ServiciosRoute._addFileChildren(
  ServiciosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ServiciosRoute: ServiciosRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
